name: MarkovChain-Release

on: [push, pull_request]

jobs:     
           
  python_lint:
    runs-on: ubuntu-latest
    name: Python lint
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: flake8 lint
        uses: py-actions/flake8@v2
        
  shell_lint:
    runs-on: ubuntu-latest
    name: Shell lint
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Shell lint
        uses: azohra/shell-linter@latest

  cpp_lint:
    runs-on: ubuntu-latest
    needs: shell_lint
    name: C++ lint
    steps:
      - uses: actions/checkout@v2
      - uses: ./myaction

  build_and_test:
    runs-on: ubuntu-latest
    needs: [cpp_lint, python_lint]
    name: Build and test
    steps:
    - name: Install gtest 
      run: sudo apt-get install g++ cmake libgtest-dev
    - uses: actions/checkout@v1
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: Make
      run: cd build && make
    - name: Run Test
      run: /home/runner/work/MarkovChain/MarkovChain/build/test/MarkovChain.test
    - name: Path
      run: cd /home/runner/work/MarkovChain/MarkovChain/build/src && ls
    - name: Generate list
      run:  /home/runner/work/MarkovChain/MarkovChain/build/src/PythonGrabber/generate_list.py  
    - name: Grabber
      run:  /home/runner/work/MarkovChain/MarkovChain/build/src/PythonGrabber/grab_reg.py
    - name: Main
      run: /home/runner/work/MarkovChain/MarkovChain/build/test/MarkovChain.info
    - name: Test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Test_artifacts
        path: /home/runner/work/MarkovChain/MarkovChain/build/test
    - name: Source artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Source_artifacts
        path: /home/runner/work/MarkovChain/MarkovChain/build/src
    - name: Data artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Data_artifacts
        path: /home/runner/work/MarkovChain/MarkovChain/build/data
    - name: Success message
      if: ${{ success() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: The job was successful.
        document: Source_artifacts.zip && Test_artifacts.zip && Data_artifacts.zip
    - name: Failure message
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: The job failed.
        document: Source_artifacts.zip && Test_artifacts.zip && Data_artifacts.zip
    
      
      
