name: GHA-frac-Release

on: [push, pull_request]

jobs:
   

  telegram_message:
    runs-on: ubuntu-latest
    steps:
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          Repository: ${{ github.repository }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          
   

  docker_lint:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: Lnt
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        
  python-lint:
    runs-on: ubuntu-latest
    name: Python lint
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: flake8 lint
        uses: py-actions/flake8@v2
        
  shell-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Shell lint
        uses: azohra/shell-linter@latest

  cpp-lint:
    runs-on: ubuntu-latest
    needs: shell-lint
    name: C++ lint
    steps:
      - uses: actions/checkout@v2
      - uses: ./myaction

  build_and_test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
    - name: Install gtest 
      run: sudo apt-get install g++ cmake libgtest-dev
    - uses: actions/checkout@v1
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: Make
      run: cd build && make
    - name: Run Test
      run: /home/runner/work/MarkovChain/MarkovChain/build/test/MarkovChain.test
    - name: Main
      if: ${{ success() }}
      run: /home/runner/work/MarkovChain/MarkovChain/build/src/MarkovChain.info
      

    
      
      
