name: GHA-frac-Release

on: [push, pull_request]

jobs:

  on_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          Repository: ${{ github.repository }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

  lint_test:
    runs-on: ubuntu-latest
    needs: on_commit
    name: Check code
    steps:
      - uses: actions/checkout@v2
      - uses: ./myaction

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest 
      run: sudo apt-get install g++ cmake libgtest-dev
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: make
      run: cd build && make
    - name: Run Test
      run: /home/runner/work/MarkovChain/MarkovChain/build/test/MarkovChain.test
      
      
