name: MarkovChain-Release

jobs:
   
  pull_request:
    runs-on: ubuntu-latest
    on: pull_request
  - name: Telegram Notify
    uses: appleboy/telegram-action@master
    with:
      to: ${{ secrets.TELEGRAM_TO }}
      token: ${{ secrets.TELEGRAM_TOKEN }}
      format: markdown
      message: |
        A new PR is raised [View all PR's](https://github.com/<user>/<repo>/pulls)       
   

        
  python_lint:
    runs-on: ubuntu-latest
    on: [push, pull_request]
    name: Python lint
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: flake8 lint
        uses: py-actions/flake8@v2
        
  shell_lint:
    runs-on: ubuntu-latest
    on: [push, pull_request]
    name: Shell lint
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Shell lint
        uses: azohra/shell-linter@latest

  cpp_lint:
    on: [push, pull_request]
    runs-on: ubuntu-latest
    needs: shell_lint
    name: C++ lint
    steps:
      - uses: actions/checkout@v2
      - uses: ./myaction

  build_and_test:
    runs-on: ubuntu-latest
    on: [push, pull_request]
    needs: [cpp_lint, python_lint]
    name: Build and test
    steps:
    - name: Install gtest 
      run: sudo apt-get install g++ cmake libgtest-dev
    - uses: actions/checkout@v1
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: Make
      run: cd build && make
    - name: Run Test
      run: /home/runner/work/MarkovChain/MarkovChain/build/test/MarkovChain.test
    - name: Generate list
      if: ${{ always() }}
      run:  /home/runner/work/MarkovChain/MarkovChain/build/src/PythonGrabber/generate_list.py  
    - name: Grabber
      if: ${{ always() }}
      run:  /home/runner/work/MarkovChain/MarkovChain/build/src/PythonGrabber/grab_reg.py
    - name: Main
      if: ${{ always() }}
      run: /home/runner/work/MarkovChain/MarkovChain/build/test/MarkovChain.info
    - name: Test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Test_artifacts
        path: /home/runner/work/MarkovChain/MarkovChain/build/test
    - name: Source artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Source_artifacts
        path: /home/runner/work/MarkovChain/MarkovChain/build/src
    - name: Data artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Data_artifacts
        path: /home/runner/work/MarkovChain/MarkovChain/build/data
    - name: Success message
      if: ${{ success() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: The job was successful.
        document: Source_artifacts.zip && Test_artifacts.zip && Data_artifacts.zip
    - name: Failure message
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: The job failed.
    
      
      
